apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "science-portal.fullname" . }}
  labels:
    {{- include "science-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "science-portal.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "science-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "science-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          # OIDC Configuration
          - name: NEXT_OIDC_URI
            value: {{ .Values.oidc.uri | quote }}
          - name: NEXT_PUBLIC_OIDC_URI
            value: {{ .Values.oidc.uri | quote }}
          - name: NEXT_OIDC_CLIENT_ID
            value: {{ .Values.oidc.clientId | quote }}
          - name: NEXT_PUBLIC_OIDC_CLIENT_ID
            value: {{ .Values.oidc.clientId | quote }}
          - name: NEXT_OIDC_CALLBACK_URI
            value: {{ .Values.oidc.callbackUri | quote }}
          - name: NEXT_PUBLIC_OIDC_CALLBACK_URI
            value: {{ .Values.oidc.callbackUri | quote }}
          - name: NEXT_OIDC_REDIRECT_URI
            value: {{ .Values.oidc.redirectUri | quote }}
          - name: NEXT_PUBLIC_OIDC_REDIRECT_URI
            value: {{ .Values.oidc.redirectUri | quote }}
          - name: NEXT_OIDC_SCOPE
            value: {{ .Values.oidc.scope | quote }}
          - name: NEXT_PUBLIC_OIDC_SCOPE
            value: {{ .Values.oidc.scope | quote }}
          # Secrets from Kubernetes Secret
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.existingSecret }}
                key: {{ .Values.secrets.keys.authSecret }}
          - name: NEXT_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.existingSecret }}
                key: {{ .Values.secrets.keys.oidcClientSecret }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
