version: '3.8'

# =============================================================================
# PRODUCTION - CANFAR MODE (EXAMPLE)
# =============================================================================
# This configuration uses CANFAR authentication (username/password)
# and CANFAR backend APIs (ws-uv.canfar.net)
#
# Copy this file to docker-compose.canfar.yml and configure as needed.
#
# Usage:
#   docker-compose -f docker-compose.canfar.yml up -d
# =============================================================================

services:
  # Next.js application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_LOGIN_API: https://ws-cadc.canfar.net/ac
        NEXT_PUBLIC_SKAHA_API: https://ws-uv.canfar.net/skaha
        NEXT_PUBLIC_SRC_SKAHA_API: https://src.canfar.net/skaha
        NEXT_PUBLIC_SRC_CAVERN_API: https://src.canfar.net/cavern
        NEXT_PUBLIC_API_TIMEOUT: "30000"
        NEXT_PUBLIC_USE_CANFAR: "true"
        NEXT_PUBLIC_ENABLE_QUERY_DEVTOOLS: "false"
    container_name: science-portal-nextjs-canfar
    restart: unless-stopped
    environment:
      # Server-side API configuration - CANFAR APIs
      - SERVICE_STORAGE_API=https://ws-uv.canfar.net/arc/nodes/home/
      - LOGIN_API=https://ws-cadc.canfar.net/ac
      - SKAHA_API=https://ws-uv.canfar.net/skaha
      - SRC_SKAHA_API=https://src.canfar.net/skaha
      - SRC_CAVERN_API=https://src.canfar.net/cavern
      - API_TIMEOUT=30000

      # Client-side configuration
      - NEXT_PUBLIC_LOGIN_API=https://ws-cadc.canfar.net/ac
      - NEXT_PUBLIC_SKAHA_API=https://ws-uv.canfar.net/skaha
      - NEXT_PUBLIC_SRC_SKAHA_API=https://src.canfar.net/skaha
      - NEXT_PUBLIC_SRC_CAVERN_API=https://src.canfar.net/cavern
      - NEXT_PUBLIC_API_TIMEOUT=30000
      - NEXT_PUBLIC_ENABLE_QUERY_DEVTOOLS=false

      # Authentication mode - CANFAR
      - NEXT_USE_CANFAR=true
      - NEXT_PUBLIC_USE_CANFAR=true

      # NextAuth configuration
      - AUTH_SECRET=${AUTH_SECRET:-REPLACE_WITH_SECURE_RANDOM_STRING}
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://localhost
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      target: nginx
      args:
        NEXT_PUBLIC_LOGIN_API: https://ws-cadc.canfar.net/ac
        NEXT_PUBLIC_SKAHA_API: https://ws-uv.canfar.net/skaha
        NEXT_PUBLIC_SRC_SKAHA_API: https://src.canfar.net/skaha
        NEXT_PUBLIC_SRC_CAVERN_API: https://src.canfar.net/cavern
        NEXT_PUBLIC_API_TIMEOUT: "30000"
        NEXT_PUBLIC_USE_CANFAR: "true"
        NEXT_PUBLIC_ENABLE_QUERY_DEVTOOLS: "false"
    container_name: science-portal-nginx-canfar
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
